from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class UsuarioPerfilesInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, nombre=None, imagen=None):  # noqa: E501
        """UsuarioPerfilesInner - a model defined in OpenAPI

        :param nombre: The nombre of this UsuarioPerfilesInner.  # noqa: E501
        :type nombre: str
        :param imagen: The imagen of this UsuarioPerfilesInner.  # noqa: E501
        :type imagen: List[str]
        """
        self.openapi_types = {
            'nombre': str,
            'imagen': List[str]
        }

        self.attribute_map = {
            'nombre': 'nombre',
            'imagen': 'imagen'
        }

        self._nombre = nombre
        self._imagen = imagen

    @classmethod
    def from_dict(cls, dikt) -> 'UsuarioPerfilesInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Usuario_perfiles_inner of this UsuarioPerfilesInner.  # noqa: E501
        :rtype: UsuarioPerfilesInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def nombre(self) -> str:
        """Gets the nombre of this UsuarioPerfilesInner.

        nombre del perfil  # noqa: E501

        :return: The nombre of this UsuarioPerfilesInner.
        :rtype: str
        """
        return self._nombre

    @nombre.setter
    def nombre(self, nombre: str):
        """Sets the nombre of this UsuarioPerfilesInner.

        nombre del perfil  # noqa: E501

        :param nombre: The nombre of this UsuarioPerfilesInner.
        :type nombre: str
        """

        self._nombre = nombre

    @property
    def imagen(self) -> List[str]:
        """Gets the imagen of this UsuarioPerfilesInner.


        :return: The imagen of this UsuarioPerfilesInner.
        :rtype: List[str]
        """
        return self._imagen

    @imagen.setter
    def imagen(self, imagen: List[str]):
        """Sets the imagen of this UsuarioPerfilesInner.


        :param imagen: The imagen of this UsuarioPerfilesInner.
        :type imagen: List[str]
        """

        self._imagen = imagen
